### ISSUE TITLE
Wont Extract and gave this message:

### ISSUE THREAD

**Issue by MysteryStew** [evandixon/DotNet3dsToolkit#25]
Exception Details:
System.IO.FileNotFoundException: Could not find file 'C:\Users\owenf\OneDrive\Desktop\extract thingy\ExeFS\banner.bnr'.
File name: 'C:\Users\owenf\OneDrive\Desktop\extract thingy\ExeFS\banner.bnr'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at DotNet3dsToolkit.Converter._Closure$__62-0.VB$StateMachine___Lambda$__0.MoveNext() in D:\TeamCity\buildAgent\work\c024c1966f7da4c7\DotNet3dsToolkit\Converter.vb:line 242
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at DotNet3dsToolkit.Converter.VB$StateMachine_62_ExtractPartition0.MoveNext() in D:\TeamCity\buildAgent\work\c024c1966f7da4c7\DotNet3dsToolkit\Converter.vb:line 256
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNet3dsToolkit.Converter.VB$StateMachine_78_ExtractCCI.MoveNext() in D:\TeamCity\buildAgent\work\c024c1966f7da4c7\DotNet3dsToolkit\Converter.vb:line 469
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNet3dsToolkit.Converter.VB$StateMachine_77_ExtractCCI.MoveNext() in D:\TeamCity\buildAgent\work\c024c1966f7da4c7\DotNet3dsToolkit\Converter.vb:line 448
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ToolkitForm.Form1.VB$StateMachine_23_btnExtract_Click.MoveNext() in D:\TeamCity\buildAgent\work\c024c1966f7da4c7\ToolkitForm\Form1.vb:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

ToolkitForm, Version=1.4.6.18, Culture=neutral, PublicKeyToken=null
C:\Users\owenf\OneDrive\Desktop\DotNet 3DS Toolkit v1.4.6\ToolkitForm.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll

DotNet3dsToolkit, Version=1.4.6.18, Culture=neutral, PublicKeyToken=null
C:\Users\owenf\OneDrive\Desktop\DotNet 3DS Toolkit v1.4.6\DotNet3dsToolkit.dll

SkyEditor.Core, Version=4.0.7.1, Culture=neutral, PublicKeyToken=null
C:\Users\owenf\OneDrive\Desktop\DotNet 3DS Toolkit v1.4.6\SkyEditor.Core.dll

System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running the program, but please report this error.

**Comment by evandixon** [comment]
Are you using a decrypted ROM? IIRC this is the error that results when the ROM's encrypted.

**Comment by MysteryStew** [comment]
yes I'm using an Ultra Sun Decrypted Rom

**Comment by evandixon** [comment]
It works fine on my own copy. Is the ROM _fully_ decrypted? Can Citra 3DS run it?
